### ISSUE TITLE
Substitution Jutsu Freezing Player

### ISSUE THREAD

**Issue by SliferSand** [HitsparkInteractive/NinOnline#11]
## Problem description

 When entering a map, if you cast Substitution Jutsu the moment you load in, there is a high probability, if not certainty, that you will freeze in place. 

## Steps to reproduce issue

 

1. Enter a map
2. Press your substitution jutsu hotkey rapidly to ensure you do it the moment you load into the map
3. Become frozen

## Observed result

 You become stuck in place, sometimes even in running position

## Expected result

 You will be unhindered and just have substitution buff on the top right as normal. 

## More details
 

**Affected Client Version:**  Unsure about old client. Inoichi client is the one I've tested this on. 

**First noticed:**  I believe this has been a thing for a few updates now, perhaps even longer. I've only recently realized that I know how to reproduce it.

## Error Logs

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by RorySoh** [comment]
Fixed in next update
