### ISSUE TITLE
Sand academy books inssue

### ISSUE THREAD

**Issue by ShihoMiyanoHaibara** [HitsparkInteractive/NinOnline#12]
## Problem description
Sand academy bounty hunting dialog issue.

Stuck in the dialog about the bounty hunting, the dialog is 
## Steps to reproduce issue

1.walk inside the academy building.
2.Press z in the bounty hunting book 

https://user-images.githubusercontent.com/88234894/127738336-770ed4c9-e07a-46b1-bfdd-c124dc92ac50.mp4

case.
3.Still pressing z until reach the last dialog.

## Observed result

https://user-images.githubusercontent.com/88234894/127738344-f94c33c8-45ef-490d-9d22-647d076bcf95.mp4

## More details

**Affected Client Version:** 

**First noticed:** 

## Error Logs

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by RorySoh** [comment]
Thank you for the bug report, we will fix this asap.
