### ISSUE TITLE
Hair bug

### ISSUE THREAD

**Issue by Zenjji** [HitsparkInteractive/NinOnline#14]
## Problem description

There is a bug with the Ashura hairstyle in the client Inochi and I do not know if other hairstyles will have it, I want you to fix that so that it looks like it was in the beginning (the old client)

## Steps to reproduce issue

1.
2.
3.

## More details

**Affected Client Version:** Inochi

**First noticed:** 

## Error Logs

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by Zenjji** [comment]
There is a bug with the Ashura hairstyle in the client Inochi and I do not know if other hairstyles will have it, I want you to fix that so that it looks like it was in the beginning

**Comment by RorySoh** [comment]
I believe this is referring to that the hair color includes the bandages?

This is not a bug, but the lack of a feature in the new client. We'll need to separate the hair from the bandage graphically and only recolor the hair. This is planned for the near future!

**Comment by Zenjji** [comment]
Thank you!
