### ISSUE TITLE
Fullscreen Wrong Resolution Bug & Zoom (Updated new vid)

### ISSUE THREAD

**Issue by Indie-Patron** [HitsparkInteractive/NinOnline#15]
**Problem description**
When in fullscreen after logging out in fullscreen, the game resolution is lowered. When you press alt-enter the resolution is correct.
If you log out in windowed and come back in and make it fullscreen, the resolution is correct.

**Steps to reproduce issue**
Log out in fullscreen at 2560x1440. Log back in. press alt-enter. 
Log out windowed 2560x1440. Log back in and press alt-enter.

**Observed Result**
Seems to be fullscreen might be an issue. Also the art on the title screen is always black, I remember seeing art once.
I've also seen other people's gameplay videos/screenshots and they can zoom out much more than I can even when the resolution seems correct. Login button is also unresponsive half the time and I need to restart the game.
See problem description.

**Expected Result**
Logging in at the same resolution I log out with.

**Affected Client Version:** Current

Note: If you think this could somehow not be game related and would want to make sure, feel free to give me some instructions. I'm not sure if anyone else has this issue, I'm hoping though.

**Comment by RorySoh** [comment]
Hi there, I've followed your steps to reproduce the issue. However, could not replicate it.
Could you provide a video demonstration of the steps you are taking so I can see if I'm missing anything?

**Comment by Indie-Patron** [comment]
https://youtu.be/bhFGMHQfpUw

My game also seems zoomed in compared to other footage I've seen.

**Comment by Indie-Patron** [comment]
https://youtu.be/RaOXm7SSWUA

![image](https://user-images.githubusercontent.com/87461110/129467328-7331bafa-a50b-48c1-ac49-4221bcd61984.png)

So when the game doesn't maximize to my monitor it looks like I guess how it should be. Not sure how this helps. But if I drag it upward and it reframes it zooms in but the UI looks correct.


I think this has to do with the game scaling to Windows UI. I have it set to 125%. In another game where I had a resolution issue, I set it to 150% and it made my game fullscreen. It's very strange. Setting it to 100% howeever did not fix it.

**Comment by RorySoh** [comment]
The zoom is set to be fixed to that zoom level if your resolution is too large. This is because we don't want players to unfairly see too much by just having a large monitor. Without it, 4K monitors can see entire maps while people on small resolutions can only see a tiny fraction of that.

With the resolutions being set to different values, is it that it's resetting to the resolution set in the Options menu?

**Comment by Indie-Patron** [comment]
> The zoom is set to be fixed to that zoom level if your resolution is too large. This is because we don't want players to unfairly see too much by just having a large monitor. Without it, 4K monitors can see entire maps while people on small resolutions can only see a tiny fraction of that.
> 
> With the resolutions being set to different values, is it that it's resetting to the resolution set in the Options menu?

I have heard of other people having this issue with some games, so you are probably right. I've seen a few people say the same thing just from Googling it too. I think it wants to take the resolution of the other monitor --- I have unplugged it before but still does it so not sure. Not sure what more to do.

**Comment by RorySoh** [comment]
> > The zoom is set to be fixed to that zoom level if your resolution is too large. This is because we don't want players to unfairly see too much by just having a large monitor. Without it, 4K monitors can see entire maps while people on small resolutions can only see a tiny fraction of that.
> > With the resolutions being set to different values, is it that it's resetting to the resolution set in the Options menu?
> 
> I have heard of other people having this issue with some games, so you are probably right. I've seen a few people say the same thing just from Googling it too. I think it wants to take the resolution of the other monitor --- I have unplugged it before but still does it so not sure. Not sure what more to do.

Can you send me the config.ini file in this location?

**Nin Online/app/data files/config.ini**

**Comment by Indie-Patron** [comment]
<?xml version="1.0" encoding="utf-8"?>
<configuration>
<startup><supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5.2" /></startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.0.0.0" newVersion="5.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Buffers" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.3.0" newVersion="4.0.3.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>

**Comment by Indie-Patron** [comment]
> > > The zoom is set to be fixed to that zoom level if your resolution is too large. This is because we don't want players to unfairly see too much by just having a large monitor. Without it, 4K monitors can see entire maps while people on small resolutions can only see a tiny fraction of that.
> > > With the resolutions being set to different values, is it that it's resetting to the resolution set in the Options menu?
> > 
> > 
> > I have heard of other people having this issue with some games, so you are probably right. I've seen a few people say the same thing just from Googling it too. I think it wants to take the resolution of the other monitor --- I have unplugged it before but still does it so not sure. Not sure what more to do.
> 
> Can you send me the config.ini file in this location?
> 
> **Nin Online/app/data files/config.ini**

[config.txt](https://github.com/HitsparkInteractive/NinOnline/files/7000683/config.txt)

**Comment by RorySoh** [comment]
Is your screen defaulting to
ResolutionWidth=2560
ResolutionHeight=1440

Whenever you restart the client?

**Comment by Indie-Patron** [comment]
> Is your screen defaulting to
> ResolutionWidth=2560
> ResolutionHeight=1440
> 
> Whenever you restart the client?

Shows in .ini & in-game

**Comment by RorySoh** [comment]
This isn't a bug then
