### ISSUE TITLE
inochi client wont open

### ISSUE THREAD

**Issue by Rephiv** [HitsparkInteractive/NinOnline#16]
########## Tue Aug 10 22:46:40 2021 - Log start
[INFO]     Tue Aug 10 22:46:40 2021 - Successful lock on  ".lock"
[INFO]     Tue Aug 10 22:46:40 2021 - Updating the patcher
[INFO]     Tue Aug 10 22:46:40 2021 - Getting the latest app version for app  "9e04617386ce3791f5ad8ff39be86d9f"
[INFO]     Tue Aug 10 22:46:40 2021 - Executing GET  "1/apps/9e04617386ce3791f5ad8ff39be86d9f/versions/latest/id"
[INFO]     Tue Aug 10 22:46:40 2021 - Downloading from  "https://api2.patchkit.net/1/apps/9e04617386ce3791f5ad8ff39be86d9f/versions/latest/id"  with timeout  10000
[INFO]     Tue Aug 10 22:46:40 2021 - Checking whether patcher is installed.
[INFO]     Tue Aug 10 22:46:41 2021 - Installation found. Checking version compatibility.
[INFO]     Tue Aug 10 22:46:41 2021 - Reading version info of installed patcher.
[INFO]     Tue Aug 10 22:46:41 2021 - Parsing version info to number -  "63"
[INFO]     Tue Aug 10 22:46:41 2021 - Local patcher id -  "04617386ce3791f5ad8ff39be86d"
[INFO]     Tue Aug 10 22:46:41 2021 - Local version - 63
[INFO]     Tue Aug 10 22:46:41 2021 - Latest version is already installed
[INFO]     Tue Aug 10 22:46:41 2021 - Starting patcher.
[INFO]     Tue Aug 10 22:46:41 2021 - Reading patcher manifest.
[DEBUG]    Tue Aug 10 22:46:41 2021 - Preparing execute target:  "C:/Program Files (x86)/Nin Online Inochi/patcher/Patcher.exe"  with arguments:  ("--installdir", "C:/Program Files (x86)/Nin Online Inochi/app", "--lockfile", "C:/Program Files (x86)/Nin Online Inochi/.lock", "--secret", "N/+T/zX/kf+d/zv/m/+X/zX/Of85/zf/O/+d/5v/Nf+d/zv/mf+N/4//m/8z/5X/Of81/5H/kf87/zf/nf+f/w==", "--online")
[INFO]     Tue Aug 10 22:46:49 2021 - Unlocking the lock file.
[INFO]     Tue Aug 10 22:46:49 2021 - Launcher has finished successfully
[INFO]     Tue Aug 10 22:46:49 2021 - Close window request.
[INFO]     Tue Aug 10 22:46:49 2021 - Allowing the window to be closed.

these are my logs please help me

**Comment by RorySoh** [comment]
Closing as there is another identical issue here
https://github.com/HitsparkInteractive/NinOnline/issues/23
Let's move there
