### ISSUE TITLE
Was training on the straw dummy and this came up

### ISSUE THREAD

**Issue by Gaara1024** [HitsparkInteractive/NinOnline#17]
## Problem description

I was training on the straw dummy on the way to the mist and I got this error message.

![image](https://user-images.githubusercontent.com/88850579/129242554-078d8ea6-b2b1-4346-9ce2-ee6d69acd205.png)

## Steps to reproduce issue

1.CLosed out of client and go back in
2.
3.

## Observed result

Nothing changed.

## More details

**Affected Client Version:** 

Inochi Client

**First noticed:** A few mins ago

## Error Logs

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by ghost** [comment]
That's a common known bug with anticheat if u want to prevent situation like that in future just move your character every few min.

**Comment by Gaara1024** [comment]
Sounds great, tysm!!!
