### ISSUE TITLE
new client black screen

### ISSUE THREAD

**Issue by scopard** [HitsparkInteractive/NinOnline#18]
## Problem description

i installed the new client and followed all the instructions but when i launch the game i only get black screen with the music and i also can click on register and other things to direct me to nins website.

## Steps to reproduce issue

When i launch the game this shows up first 
![Screenshot_1](https://user-images.githubusercontent.com/87023290/129268346-6a2e8857-69fc-4915-950f-b05e05783346.png)

But the patchkit still shows up when i hit play the game launches but the screen is black like i said above
![Screenshot_2](https://user-images.githubusercontent.com/87023290/129268493-46b802ca-cb03-4eb1-80f8-54b96eb859ea.png)

## More details

**Affected Client Version:** 

**First noticed:** 

## Error Logs

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by RorySoh** [comment]
Have you tried BR client?

**Comment by scopard** [comment]
> Have you tried BR client?

Yeh i also tried it, it has the same problem.

**Comment by RorySoh** [comment]
@scopard Can you click the "View Problem Details" and send that as well as any log files in the logs folder?
