### ISSUE TITLE
NPC Jutsus

### ISSUE THREAD

**Issue by HageshiH** [HitsparkInteractive/NinOnline#20]
## Problem description

Jutsus cast/used by NPCs, mainly bosses do not "pop"/remove substitutions. 

## Steps to reproduce the issue

1. Cast any Subsitutions, Water Substitution or Speed Mirage.
2. Attack an NPC that can cast a Jutsu (e.x Dark Slicing Wind by Dark Weasel)
3. You are warped but the sub doesn't go away.

## Observed result

You keep the substitution for the remainder of its time unless you get meleed by the NPC.
The WORST is the Wind Barrage Jutsu used by Raccoon Bandits and Raein bandit inside the bandit's house THEY DO DAMAGE on top of not removing the sub and warping you. It can also bug you in a way that it WILL hit you multiple times with the barrage and deal upwards to 1000+ damage.

## Expected result

When the player is hit by an NPC jutsu, he's warped, the sub goes away and DOES NOT receive damage by the Wind Barrage.

## More details

There's no limit to the range of certain Bandit/Boss NPC jutsus which can pop your substitution. 

**Affected Client Version:** 
BOTH

OLD

**First noticed:** 
Always been the same.

## Error Logs

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by RorySoh** [comment]
Fixed in next version.
