### ISSUE TITLE
Jutsu Description font too big

### ISSUE THREAD

**Issue by TypicalCrusader** [HitsparkInteractive/NinOnline#21]
## Problem description

Text in Jutsu description is too big which causes the text to exit 

## Steps to reproduce issue

just read jutsu description

## Observed result

jutsu description text font is too big which causes the text to exceeding textbox boundaries (i attached the picture of what is a problem
![Bez tytułu](https://user-images.githubusercontent.com/66215393/129371465-2a68959c-47eb-4cbe-b0f6-7b0aa82fbb7f.png)
)

## Expected result

text not exceeding the visible texbox boundaries

## More details

**Affected Client Version:** INOCHI CLIENT

**First noticed:** Today after patch

## Error Logs

**Comment by RorySoh** [comment]
Fixed in next update
