### ISSUE TITLE
Inochi client doesnt open

### ISSUE THREAD

**Issue by seventyv45** [HitsparkInteractive/NinOnline#23]
inochi client doesnt open after patcher

## Steps to reproduce issue

1.run the exe
2.game patches
3.after i click play it closes and nothing happens

## Observed result

after i run the game as a administrator  it patches and then disappears nothing happens.

## Expected result

wanted the game to open

## More details

**Affected Client Version:** 

inochi client 

didnt work before or after the update 

## Error Logs

<details><summary>View details</summary>

########## Fri Aug 13 16:53:46 2021 - Log start
[INFO]     Fri Aug 13 16:53:46 2021 - Successful lock on  ".lock"
[INFO]     Fri Aug 13 16:53:46 2021 - Updating the patcher
[INFO]     Fri Aug 13 16:53:46 2021 - Getting the latest app version for app  "9e04617386ce3791f5ad8ff39be86d9f"
[INFO]     Fri Aug 13 16:53:46 2021 - Executing GET  "1/apps/9e04617386ce3791f5ad8ff39be86d9f/versions/latest/id"
[INFO]     Fri Aug 13 16:53:46 2021 - Downloading from  "https://api2.patchkit.net/1/apps/9e04617386ce3791f5ad8ff39be86d9f/versions/latest/id"  with timeout  10000
[INFO]     Fri Aug 13 16:53:47 2021 - Checking whether patcher is installed.
[INFO]     Fri Aug 13 16:53:47 2021 - Installation found. Checking version compatibility.
[INFO]     Fri Aug 13 16:53:47 2021 - Reading version info of installed patcher.
[INFO]     Fri Aug 13 16:53:47 2021 - Parsing version info to number -  "63"
[INFO]     Fri Aug 13 16:53:47 2021 - Local patcher id -  "04617386ce3791f5ad8ff39be86d"
[INFO]     Fri Aug 13 16:53:47 2021 - Local version - 63
[INFO]     Fri Aug 13 16:53:47 2021 - Latest version is already installed
[INFO]     Fri Aug 13 16:53:47 2021 - Starting patcher.
[INFO]     Fri Aug 13 16:53:47 2021 - Reading patcher manifest.
[DEBUG]    Fri Aug 13 16:53:47 2021 - Preparing execute target:  "C:/Program Files (x86)/Nin Online/patcher/Patcher.exe"  with arguments:  ("--installdir", "C:/Program Files (x86)/Nin Online/app", "--lockfile", "C:/Program Files (x86)/Nin Online/.lock", "--secret", "N/+T/zX/kf+d/zv/m/+X/zX/Of85/zf/O/+d/5v/Nf+d/zv/mf+N/4//m/8z/5X/Of81/5H/kf87/zf/nf+f/w==", "--online")
[INFO]     Fri Aug 13 16:53:47 2021 - Unlocking the lock file.
[INFO]     Fri Aug 13 16:53:47 2021 - Launcher has finished successfully
[INFO]     Fri Aug 13 16:53:47 2021 - Close window request.
[INFO]     Fri Aug 13 16:53:47 2021 - Allowing the window to be closed.

</details>

**Comment by Saltydiceg** [comment]
same error as mine. i hope they resolve this issue.

**Comment by RorySoh** [comment]
Hi there, could your anti-virus/firewall program be deleting the client when it is downloaded?
Can you check your installation folder to see if it's there?
If it is, can you try running it directly to see if it runs.

**Comment by Saltydiceg** [comment]
Same problem like him, after installation. My antivirus was disabled completely, but it might have been a patcher problem.

After running the patcher it decompressed with reduced file size Im not sure if has something to do with it. 

I do have the required .Net installed already this is the step by step procedure I've done so far. 

Theres no error warning but the game just closes after server selection.

![logincrash](https://user-images.githubusercontent.com/88971942/129540460-8b62629a-dd2f-42a4-947c-d61683476e82.jpg)

**Comment by michaelsakharov** [comment]
When this happens is it Immediately after pressing the server select button or has a small pause like it's connecting but then crashes?

**Comment by seventyv45** [comment]
mine happens immediately after pressing play,also i disabled my antivirus and allowed the exe through firewall still same issue

**Comment by Saltydiceg** [comment]
> When this happens is it Immediately after pressing the server select button or has a small pause like it's connecting but then crashes?

For me It happens immediately without warning. no connecting or crashes. I do have the same error log as the original poster.

**Comment by RorySoh** [comment]
> Same problem like him, after installation. My antivirus was disabled completely, but it might have been a patcher problem.
> 
> After running the patcher it decompressed with reduced file size Im not sure if has something to do with it.
> 
> I do have the required .Net installed already this is the step by step procedure I've done so far.
> 
> Theres no error warning but the game just closes after server selection.
> 
> ![logincrash](https://user-images.githubusercontent.com/88971942/129540460-8b62629a-dd2f-42a4-947c-d61683476e82.jpg)

Your installation of Nin Online is suspiciously small. I believe this is still due to the anti-virus issue.
What anti-virus software do you have enabled?

https://www.ninonline.org/forum/troubleshoot/

**Comment by RorySoh** [comment]
> mine happens immediately after pressing play,also i disabled my antivirus and allowed the exe through firewall still same issue

https://www.ninonline.org/forum/troubleshoot/
Follow the steps for the last one here.
Let me know if you can find the NinOnline.exe file too

**Comment by seventyv45** [comment]
followed every step but still same issue

**Comment by Saltydiceg** [comment]
> > Same problem like him, after installation. My antivirus was disabled completely, but it might have been a patcher problem.
> > After running the patcher it decompressed with reduced file size Im not sure if has something to do with it.
> > I do have the required .Net installed already this is the step by step procedure I've done so far.
> > Theres no error warning but the game just closes after server selection.
> > ![logincrash](https://user-images.githubusercontent.com/88971942/129540460-8b62629a-dd2f-42a4-947c-d61683476e82.jpg)
> 
> Your installation of Nin Online is suspiciously small. I believe this is still due to the anti-virus issue.
> What anti-virus software do you have enabled?
> 
> https://www.ninonline.org/forum/troubleshoot/

Yes, I also followed the troubleshooting guide. i also I tried disabling everything firewall & antivirus in hopes it would work. 

(repeating reinstalling over & over again lol **) 

I am a new player but i played the previous client version before without any issues.

Here is the version of my framework.  Hope it helps for those who also has same issue as ours.
![netversion](https://user-images.githubusercontent.com/88971942/129706584-0227bd6d-ee9f-4a16-948b-ef2d8afffd7c.jpg)

**Comment by Saltydiceg** [comment]
Maybe the reason why it doesn't work at all. after running the patch, the contents from this folder disappears after the new update.

I think these are 5 files from 3.5.0.0 version of the game. 

Path: C:\Program Files (x86)\Hitspark\Nin Online\app\ .downloads 

-content-34
-content-meta-34
-diff-35
-diff-meta34
-diff-meta35


Running the patcher updates and overwrites these files with new files. Unfortunately also the new contents in this folder disappears after the patch and running the game. ( Idk whats the reason behind it.) maybe some ppl with tech knowledge knows

So what i did is separate these old files on a different folder then paste it on the same directory run the app to test it. 

I got past the server select screen and requires me a 3.5.0.1. the new update

Perhaps something wrong with the contents in this folder the new ones disappears instead of overwriting the old files.


![3501](https://user-images.githubusercontent.com/88971942/129774076-0fb372f6-022c-418e-a9ca-224ddcbeac79.jpg)

**Comment by Saltydiceg** [comment]
Sorry i really thought it was a patcher issue " (i feel like an idiot sometimes) :(".  

This guide helped me just follow the guide by changing DNS. 8.8.8.8 and 8.8.4.4

https://nestify.io/blog/the-easy-guide-to-fix-dns_probe_finished_nxdomain-error/

**Comment by seventyv45** [comment]
didnt work for me

**Comment by RorySoh** [comment]
Sorry if you're having issues with the updater not being able to get all the files you need to play, I can't really help.
Unless you can manage to get the files all there and still it doesn't work, I don't know how we can help.
