### ISSUE TITLE
Several problems with Leaf village summit map

### ISSUE THREAD

**Issue by TypicalCrusader** [HitsparkInteractive/NinOnline#24]
## Problem description

I wanted to check what the temple is. and i got stuck in the entrance to the temple (also known in this report as summit building), 

## Steps to reproduce issue

Summit Building doors stuck issue
1. Dont be in the Corps that is needed for you to enter the Summit Building
2. Try to enter the Building
3. You cant leave the entrance (i was somehow able to wriggle out from the entrance)
NOTE: THIS APPLIES MORE OR LESS TO ALL BUILDINGS THAT REQUIRE CORPS MEMBERSHIP
![Bez tytułu](https://user-images.githubusercontent.com/66215393/129393089-3aaaf8de-78e8-4349-a735-db779ddd4855.png)

Graphical Issue on the map's Edge
just go the right corner of the platform to see this
![Bez tytułu2](https://user-images.githubusercontent.com/66215393/129393065-c7e4baeb-6e3f-4c8e-bb9a-50cf31e41926.png)

## Observed result

For Stuck issue, you cant leave the entrance 
For Graphical, i see black lines bleeding into terrain as on a picture posted before

## Expected result

For Stuck issue, i should be able to leave the entrance 
For Graphical, not seeing black line

## More details

**Affected Client Version:** Not sure, it does affect inoichi

**First noticed:** Today after update that decapitated old client was released

## Error Logs

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by RorySoh** [comment]
Fixed, thank you!
