### ISSUE TITLE
Randomly Disconnecting from the game.

### ISSUE THREAD

**Issue by Mizxry** [HitsparkInteractive/NinOnline#25]
## Problem description

It started when I used the command '/mapcache' and it caused my game to completely crash. I then tried it three more times which all caused it to disconnect me not crash. So I tried logging back on 2-3 times after I finished that test and now the game diconnects me less than 2 mins after logging in.

## Steps to reproduce issue

1.Type in '/mapcache'
2. Repeat step on 3 times to see if the disconnecting continues
3.Try to log back in after your mapcache tests.

## Observed result

1. It sends me to the login page saying "Your already logged in", "Someone is logged in as you" or "Connection Lost".
                                                                                             or
 2. It completely crashes the game.                                                                                            

## Expected result

I expect that the game would be able to run smoother for me without this disconnecting issue once this is sorted out.

## More details

**Affected Client Version:** Inochi Client

The problem was present for me on the pervious 3 versions of the Inochi client

**First noticed:** Long before the present update.

## Error Logs

<details><summary>View details</summary>

[errors.txt](https://github.com/HitsparkInteractive/NinOnline/files/6984129/errors.txt)

</details>

**Comment by RorySoh** [comment]
Hi, are you sharing accounts and is someone else trying to login?
That would disconnect you with that message, nothing else in the code should do that.

**Comment by michaelsakharov** [comment]
If you were to attempt to log in really really fast, you may have attempted to relog before the server properly disconnected your character. That's the only other way I can think of that could trigger that message.

**Comment by Mizxry** [comment]
> Hi, are you sharing accounts and is someone else trying to login?
> That would disconnect you with that message, nothing else in the code should do that.

Hey, no one has the log in to that account but me, so wolf's respond might be the solution thank you for the reply I'll take my time with relogging.

**Comment by Mizxry** [comment]
> If you were to attempt to log in really really fast, you may have attempted to relog before the server properly disconnected your character. That's the only other way I can think of that could trigger that message.

Alright thank you for the response, I'll take my time when logging in.

**Comment by RorySoh** [comment]
@michaelsakharov We should make the messages clearer.
