### ISSUE TITLE
My account is unable to be logged into in-game

### ISSUE THREAD

**Issue by ryanara3** [HitsparkInteractive/NinOnline#27]
## Problem description

I can log into the game on the forums, but it will not allow me to log into the account in-game. At first it had a different error code than the typical "Try again later" one, but I wasn't fast enough to screen shot it and it hasn't since given me that one. Every time I encounter a case where I can't log in and get the standard "Try again later" message, it will work later. But this is the only case where another error code happened first and has since to let me into the game. First encountered on 08/15/2021 @ around 0030 est.

## Steps to reproduce issue

There are no steps to follow to re-create this.

1.
2.
3.

## Observed result

Can't log in

## Expected result

-

## More details

**Affected Client Version:** New client

**First noticed:** 

## Error Logs

There was no crash, therefor no error log

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by michaelsakharov** [comment]
Next time you get a "Try Agian Later" message, try taking a picture and posting it here.
Usually, they contain more information that can help narrow down what's wrong.

**Comment by RorySoh** [comment]
What is your account?

**Comment by RorySoh** [comment]
Can you tell me the account name as well so I can see if it's an account issue or client issue?
