### ISSUE TITLE
Game crashes when entering maps. 

### ISSUE THREAD

**Issue by Moonshine6475** [HitsparkInteractive/NinOnline#28]
## Problem description

The game crashes when I enter a map I haven't before, then proceeds to crash every time I attempt to log back in. The client shows the map change animation, becomes stuck on a black screen, then closes itself. 

## Steps to reproduce issue

1. It has to be a previously unexplored map/building, usually a larger sized one. 
2. Attempt to enter the map 
3.The screen should enter the map change animation, but become stuck. 

## Observed result

 
The mouse then shows a loading sign, and the client closes itself. After that, every attempt to log back into the game becomes stuck halfway through the map change so that the client is either partially or completely black. Then, it crashes again. 
![image](https://user-images.githubusercontent.com/46656314/129595596-899b4524-c365-4ed0-b655-1140f0f0d607.png)

## Expected result

I expected to enter the map.

## More details

**Affected Client Version:**  Inochi Client 

**First noticed:**  I'm fairly new to this game, but I noticed it when I entered the ambush forest map on the first day. 

## Error Logs

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by RorySoh** [comment]
Are you running out of disk space?

**Comment by Moonshine6475** [comment]
I have 400 GB free no i dont think so

**Comment by RorySoh** [comment]
Can you check your error logs folder for a error txt file?

**Comment by Moonshine6475** [comment]
I checked, it's empty.

**Comment by RorySoh** [comment]
Cannot help without more information
