### ISSUE TITLE
Casino third slot bugged

### ISSUE THREAD

**Issue by Daftzy** [HitsparkInteractive/NinOnline#31]
The Okada's debt quest, requires you to profit 1000 ryo from the casino ive been trying for 2 weeks by now to get the mission, the only reasonable way its to get the jackpot, otherwise the math will bring you down to 0 from 300 as has done for me several times.

After 5 hours of straight trying Ive started to screenshot every double 7-7-X I was getting from the machine, and never got a single number 7 at the third slot, not even X-X-7, also multiple times when it was about to get a 7 on the third slot, it stop for 10ms on a 7 then switched to a leaf.

After 2 weeks of hard trying and watching multiple ppl ask about this bug on discord I'm opening a case so it goes unforgotten, a lot of players would love to deliver this quest.. special us the new ones.

## Steps to reproduce issue

1. Depends on the character...
2. Go to tanzaku crank machines
3. Try to do the quest Okada's debt between the machines or the dices
4. See how you will never get a 7 under the third slot of the machine
5. Get your quest stuck forever.

## Observed result

Everytime a 7 might pop on a third slot it switches to a leaf

## Expected result

to get a number 7 on the third slot of the machine, even if its not the jack pot accordingly to statistics possibilities

## More details

**Affected Client Version:** 
New client, never ever been on the old one since i started not long ago

**First noticed: The day i went to tanzaku with my friend to do the mission, he completed it in 30mins, other 2 guys got 777 in front of me, and i stayed there for several days trying even today i gave it a shot and nothing changes** 

## Error Logs

I've no error logs for this since seems to be an inside character issue.

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by RorySoh** [comment]
It's a visual bug that's been fixed in the latest update.
