### ISSUE TITLE
Shop automatically buying stuff

### ISSUE THREAD

**Issue by Leighray** [HitsparkInteractive/NinOnline#34]
## Problem description

Clothes shop automatically buying items

## Steps to reproduce issue

No idea, I'm not opening it again to lose more ryo, I went in was checking how stuff would look on me, next thing I notice 2 scarfed sand robes in my inventory.

## Observed result

 I went in was checking how stuff would look on me, next thing I notice 2 scarfed sand robes in my inventory.

## Expected result

Not waste my money on things I never bought myself.

## More details
First noticed today, new client, newest everything. 

## Error Logs

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by Leighray** [comment]
![Capture](https://user-images.githubusercontent.com/89135891/130044008-9fdc27fd-921b-42ca-9407-f6a696f01134.PNG)
if possible id like my money back, they cost 2500 each I sold two of them back so 5000-2500= 2500

**Comment by Leighray** [comment]
I also had fan equipped, if it changes anything idk

**Comment by RorySoh** [comment]
It happens if you double click an item in the shop
