### ISSUE TITLE
I can't play the game

### ISSUE THREAD

**Issue by BogdanDBI** [HitsparkInteractive/NinOnline#35]
## Problem description

Game keeps crashing whenever im in server selection screen
https://imgur.com/a/Ct26IRa
First time after reinstalling i managed to get in, afterwards it kept crashing just as it used to

## Steps to reproduce issue

1.
2.
3.

## Observed result

 Nin online stops working

## Expected result

 to log me in so i can play

## More details
 I tried reinstalling the game and it did the same thing

**Affected Client Version:** INOCHI

**First noticed:**  Yesterday after the update

## Error Logs

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by RorySoh** [comment]
@michaelsakharov I believe this has to do with the IP getting change

**Comment by michaelsakharov** [comment]
Hmm, IP getting shouldnt be able to crash anymore, since its all under a try catch, worse case it returns "" which is fine.

**Comment by RorySoh** [comment]
@michaelsakharov I know it shouldn't. But the version before this was fine for him, and we made very little changes besides the IP change.

**Comment by RorySoh** [comment]
@BogdanDBI Did the latest update fix it for you?
