### ISSUE TITLE
Ping?, Client Side?, Server Side? Issue - People showing One map tile to the right of their targeted position

### ISSUE THREAD

**Issue by TypicalCrusader** [HitsparkInteractive/NinOnline#36]
## Problem description

People show one map tile to the right of their true? position.
![Bez tytułu](https://user-images.githubusercontent.com/66215393/130052088-b113b378-8669-4fab-965a-3acba250d71a.png)

## Steps to reproduce issue

From my observations this happens for people who are transformed using the Transformation Jutsu.

## Observed result

Im Targetting an empty space and see a person one map tile to the right

## Expected result

I should see the person in a same tile as the target

## More details

**Affected Client Version:** INOCHI CLIENT

**First noticed:** 19.08.2021 11 AM CET

## Error Logs

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by RorySoh** [comment]
There was an invisible player there, they used transformation technique.
There was a bug where transformation technique could make someone invisible. It's fixed now.
