### ISSUE TITLE
Toyozo & Yori Dialogue Name Broken

### ISSUE THREAD

**Issue by TypicalCrusader** [HitsparkInteractive/NinOnline#37]
## Problem description
Dialogue Name of Toyozo and Yori is Borked

## Steps to reproduce issue

Just talk to Toyozo  & Yori

## Observed result

![Bez tytułu](https://user-images.githubusercontent.com/66215393/130117811-f2988b1a-fd2c-43e1-ba68-0c312abdf723.png)
![Bez tytułu](https://user-images.githubusercontent.com/66215393/130118259-1a211c48-2ac5-4682-a295-5765606a8eea.png)

## Expected result

Toyozo & Yori should have their name

## More details

**Affected Client Version:** INOCHI CLIENT 

**First noticed:** 19.08.2021 19:42 CET

## Error Logs

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by RorySoh** [comment]
Fixed the names around the leaf village. Thank you!
Let us know if you find any more.

@michaelsakharov Note there's an annoying bug with the event editor, if you remove event Index 3, all the events in Index 4,5,6,7,8 onwards will screw up their references to the names for dialogues.
