### ISSUE TITLE
Adamantine Staff Range Bugged

### ISSUE THREAD

**Issue by Zabuh** [HitsparkInteractive/NinOnline#38]
### **Problem description**
Adamantine staff does not have 2 tile range on players but it has 2 tile range on mobs

### **Steps to reproduce issue**
stand 2 tiles away from a mob using an adamantine staff and auto attack
reciprocate this on a player and it will not work 

### **Expected result**
Adamantine staff 2 tile reach on both players and mobs

### **More details**
2 tile range on players doesnt work no matter what client you are using

**First noticed:** Since the Adamantine staff has been first dropped

**Comment by RorySoh** [comment]
Fixed in next update
