### ISSUE TITLE
Rogue pixels

### ISSUE THREAD

**Issue by Leighray** [HitsparkInteractive/NinOnline#46]
Hey, idk if this belongs here and fuck me if it don't but thought that we could maybe submit all in game sprites that got rogue pixels here.

Big Scarab moving animations got rogue pixels left right up and down (has to be chasing you to see them)

**Comment by Su5hicz** [comment]
![image](https://user-images.githubusercontent.com/57494027/130487973-f76b6048-aff5-4bf1-85bb-f80f3b490304.png)
![image](https://user-images.githubusercontent.com/57494027/130487981-238a8972-1fe3-4c02-b149-be0e714211bd.png)
![image](https://user-images.githubusercontent.com/57494027/130487989-7d52d233-5eee-4a51-b8c6-636a1725699c.png)

**Comment by RorySoh** [comment]
Both fixed in next version
