### ISSUE TITLE
Some sprites are out of boundaries

### ISSUE THREAD

**Issue by Su5hicz** [HitsparkInteractive/NinOnline#47]
## Problem description

Few sprites. snake summoning is the most known go out of bounds and appear on places where they are not supposed to

## Steps to reproduce issue

Summon a snake, its the easiest to see this issue

## Observed result

Pixels out of boundaries

## Expected result

Pixels where they are supposed to be

**Affected Client Version:** INOCHI CLIENT
![obrázek_2021-08-23_190354](https://user-images.githubusercontent.com/57494027/130487803-85e923c7-dbe8-423f-85e1-e322d609d6a5.png)
![obrázek_2021-08-23_190400](https://user-images.githubusercontent.com/57494027/130487815-a5bc28e5-2b89-4c5c-afd2-5ed5884daef1.png)
![obrázek_2021-08-23_190409](https://user-images.githubusercontent.com/57494027/130487836-c088ddff-ed64-47bd-a302-bbf6c67683c3.png)

**Comment by RorySoh** [comment]
Fixed in next version
