### ISSUE TITLE
afterupdate or new cpu enemies are jumpy

### ISSUE THREAD

**Issue by Gaara1024** [HitsparkInteractive/NinOnline#48]
## Problem description

I got a new CPU and there was a new update so I am not sure which caused the problem. The enemies jump from one tile to another. 

## Steps to reproduce issue

1. Find enemy, it happens
2.
3.

## More details
I think if I went over my settings it someone that might fix the problem.

**Affected Client Version:** 

Inochi Client

I first noticed it today

**Comment by RorySoh** [comment]
We made the movement more consistent with what they actually are doing on the server. I'll try to improve it to move tile to tile slower.
