### ISSUE TITLE
House Invite List cleans

### ISSUE THREAD

**Issue by Daftzy** [HitsparkInteractive/NinOnline#49]
Everytime theres a small update or a the server closes I've to re-invite my friends to my house for some reason, I've tried making them co-owner, guest but still gets empty.

(taking the opportunity to suggest adding access to houses with a second floor....)

1. own a house
2. Invite people (not open to public)
3. wait for the game to close
4. try to enter the house again, not being able, need to re-invite

## Observed result

My invite list gets cleaned every single day at this point

## Expected result

No need to re-invite the same ppl to my property everytime something weird cleans my invite list

## More details

**Affected Client Version:** newest client

**First noticed:** 

## Error Logs
i doubt theres error logs related, more like DB issue linking between instances

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by michaelsakharov** [comment]
This should be fixed for the next server update.
