### ISSUE TITLE
Slow cast jutsus cause the screen to distort and move backwards.

### ISSUE THREAD

**Issue by Enarta** [HitsparkInteractive/NinOnline#5]
## Problem description

When using a jutsu that is casted through a "Slow run cast", if the user is slowed from an outside source or walking, the character will appear to move backwards. Video:

https://user-images.githubusercontent.com/53319981/125381533-b26cc780-e359-11eb-9e4b-b5e05b7713fb.mp4

## Steps to reproduce issue

1. The easiest way to reproduce this bug is simply toggle your running to start walking.

2. Once you do that, continue walking and cast the slow run cast jutsu, such as advanced lightning cutter or fire wall. 

Alternative bug reproduction:

1. Make sure your run is toggled ON.

2. Have another player or enemy hit you will an ability that inflicts the slow debuff.

3. Cast the slow run cast jutsu, while slowed and attemping to move.

## Observed result

Your character will appear to move backwards instead of the direction you are attempting to move. 

## Expected result

The camera will follow your character normally and you will move in the direction you are intending go.

## More details

This bug has been around since the introduction of slow run casts. 

**Affected Client Version:** BOTH

Every client since the introduction of the slow run cast feature (As of July 12th, 2021)

**First noticed:** The same day slow run casts were introduced. 

## Error Logs

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by RorySoh** [comment]
Thank you, yes this is actually just bad math.
We will fix this when the old client is deprecated.

**Comment by RorySoh** [comment]
Fixed on next update
