### ISSUE TITLE
Not Equipping Swordsman Premium Hairstyle When Selected

### ISSUE THREAD

**Issue by 7kuroh** [HitsparkInteractive/NinOnline#50]
When I put on the Swordsman Premium Hairstyle cash shop item it instead equips the Sasu Hairstyle.

**Comment by RorySoh** [comment]
Sorry we'll take awhile to fix this because our editors are bugged.

**Comment by Kabutomaruu** [comment]
I bought the Swordsman Premium Hairstyle today as it was available in the Cash Shop, but there was no note on the bug.
Hope it gets fixed sooner then later and maybe remove it from the shop till it's fixed.

**Comment by RorySoh** [comment]
@michaelsakharov Any way for us to manually fix the data, or expedite this?

**Comment by RorySoh** [comment]
> I bought the Swordsman Premium Hairstyle today as it was available in the Cash Shop, but there was no note on the bug.
> Hope it gets fixed sooner then later and maybe remove it from the shop till it's fixed.

Do you guys want a refund for the time being?

**Comment by Kabutomaruu** [comment]
> 
> 
> > I bought the Swordsman Premium Hairstyle today as it was available in the Cash Shop, but there was no note on the bug.
> > Hope it gets fixed sooner then later and maybe remove it from the shop till it's fixed.
> 
> Do you guys want a refund for the time being?

Yes please. Shall I write a support ticket or contact someone?
IGN: Kabutomaru

**Comment by RorySoh** [comment]
I've refunded it to Ninja Credit for you. What about @7kuroh ?

**Comment by RorySoh** [comment]
This has been temporarily resolved
