### ISSUE TITLE
Wierd Dialogue Delay Bug

### ISSUE THREAD

**Issue by TypicalCrusader** [HitsparkInteractive/NinOnline#52]
## Problem description

Dialogue box stating that i need at least level 30 shows. This one dialogue **only** shows when i hit that star thing and go to the lower left corner of the leaf mission room

## Steps to reproduce issue

1.Hit The glowing star thingy that is in leaf mission room
2. go to the lower left corner of the room
3. wait a short while
4. you see a dialogue

## Observed result

![Bez tytułu](https://user-images.githubusercontent.com/66215393/131104789-d119eac1-41e5-4651-84ec-d6aed6a17764.png)

## Expected result

Dialogue Should appear when i use attack/interation button on npc

## More details

**Affected Client Version:**  INOCHI CLIENT

**First noticed:** 27.08.2021 11:26 CET

## Error Logs

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by RorySoh** [comment]
I believe this was just due to lag
