### ISSUE TITLE
Unable to unblock players.

### ISSUE THREAD

**Issue by Enarta** [HitsparkInteractive/NinOnline#53]
![Button that I am clicking](https://user-images.githubusercontent.com/53319981/131134556-26c6fd54-3b6c-4181-965f-5728db7fb413.png)

## Problem description

A few years ago I blocked an account and any time I unblocked it, it would eventually revert back to being blocked. Today when I try to unblock them it results in nothing happening. The player is not unblocked after clicking the option.

**Comment by RorySoh** [comment]
If you used the /block command, you have to use it again, and I believe it's case sensitive, so if you did /block theavatar you have to do it again the same way.

We will improve this soon

**Comment by RorySoh** [comment]
Fixed in next version
