### ISSUE TITLE
Bubble Shark Bomb Jutsu Hitbox bugged

### ISSUE THREAD

**Issue by ashonfire** [HitsparkInteractive/NinOnline#55]
https://user-images.githubusercontent.com/76893835/131206778-afae7956-83ab-42ae-8d33-a8023ca19866.mp4

## Problem description

The hit box on the Bubble Shark Bomb Jutsu is bugged a shown in the two videos.

https://user-images.githubusercontent.com/76893835/131206975-70b65f80-f0ee-4465-a3b8-1d39c3e49e1d.mp4

</details>

**Comment by RorySoh** [comment]
This has been fixed

**Comment by ashonfire** [comment]
Looking good!
