### ISSUE TITLE
Black gloves display over the hermit cape

### ISSUE THREAD

**Issue by BluuCrow** [HitsparkInteractive/NinOnline#56]
Black gloves display over the hermit cape

![Glove 1](https://user-images.githubusercontent.com/89708432/131230328-5e4d5645-380b-4108-b347-19c311a2114e.PNG)

![Glove 2](https://user-images.githubusercontent.com/89708432/131230331-18b6ba73-60b5-4345-88b7-43cfe717819b.PNG)

**Comment by RorySoh** [comment]
This is unfortunately just a bi-product of our limited layering system and won't be fixed.
