### ISSUE TITLE
Nin Online Launcher/Client not opening

### ISSUE THREAD

**Issue by DeepuCharm** [HitsparkInteractive/NinOnline#58]
Hello Rory... I hope you're doing okay and its great to see how much you've improved the game's features with your tons of new updates. 

Now about my issue.. First of all,I recently upgraded my potato PC to a little better one
My current one ---  Windows 10 Pro x64 bit OS, Core 2 Duo processor, 4 GB RAM (Still no graphics card tho)
And my windows is fully up-to-date + I have all the latest versions of .Net Framework and Visual C++ and DirectX installed

Now.. when I'm trying to launch NinOnline (from both launcher/Client directly),It's not launching at all but I got an error log in the data files folder,lemme show you here.

[errors.txt](https://github.com/HitsparkInteractive/NinOnline/files/7072742/errors.txt)

This is the error I'm getting.. Idk if its graphics related,I don't have a graphics card but I have Intel G41 Express Chipset already.
It would be helpful if you can help me fix this problem... Thanks again.

**Comment by RorySoh** [comment]
You seem to be unable to render shaders because of the lack of a graphics card.
There's something you can try, delete the contents of your shader folder and see if it runs.
