### ISSUE TITLE
agility affecting ghost hits on sword.

### ISSUE THREAD

**Issue by Dagonian15** [HitsparkInteractive/NinOnline#60]
## Problem description

having some agility stats invested affects the ghost hits the character does with sword.

## Steps to reproduce issue

1. Invest some agility into your stats( in my case 35agi).
2. Equip a sword.
3. hold z with sword or try to do jutsus and do a normal atk right after.

## Observed result

The 2nd hit of everything, being it normal atack or jutsus will 100% miss.

## Expected result

The sword hit should land/do dmg.

## More details

Im a wm/tai and agility is part of my build, one thing i notice is that 1 in every 2 normal hits i ghost hit, after every jutsu i use i 100% ghost hit, as i went to test this out on another account without agi, i didnt ghost hit as much, probably 1 in 10 hits, bringing me to the conclusion that the agility that should be increasing the sword atk rate is not registering that small boost in speed thus making the animation happen sooner but ghost hitting.

**Affected Client Version:** dont know, can only use INOCHI CLIENT.

Havent used the old client in a while, so im not sure if it was affecting it.

**First noticed:** i noticed this a while ago, maybe like 3months, im not sure about the timing. Always thought it was a ping related issue.

**Comment by RorySoh** [comment]
Good observation. It's likely. I'll look into it!

**Comment by RorySoh** [comment]
https://github.com/HitsparkInteractive/NinOnline/issues/84#issue-1004917764

**Comment by RaitouNin** [comment]
Thanks for the update, looking forward to where this goes.
