### ISSUE TITLE
Persistent windowed resolution

### ISSUE THREAD

**Issue by Su5hicz** [HitsparkInteractive/NinOnline#63]
## Problem description

Window resolution/size is not persistent after reopening the application

## Steps to reproduce issue

1. Set your game into windowed mode
2. Resize your window
3. Close and open the application again

## Observed result

The window is in default 800x600 resolution.

## Expected result

Same window size as when I closed the app.

## More details
This is pretty annoying since every time you resize the window you have to wait for a second or two for the window to reload.

**Affected Client Version:**

INOCHI CLIENT

**Comment by RorySoh** [comment]
Not a bug, scaling the window is temporary, if you want to set a custom resolution do it in the options panel or directly from the configuration file.
