### ISSUE TITLE
Risky Blade Dance cancels Jutsu cast without having any stun/silence/knockback/snare. 

### ISSUE THREAD

**Issue by Enarta** [HitsparkInteractive/NinOnline#64]
https://user-images.githubusercontent.com/53319981/132043585-eeebeed2-21a2-447d-808e-c01162855a91.mp4

## Problem description

When Risky Blade Dance lands on an enemy who is casting a jutsu, their jutsu will be cancelled despite there being no cc applied.

## Steps to reproduce issue

1. Enemy is casting a jutsu
2. Enemy is hit by risky blade dance
3. Their jutsu is cancelled.

## Observed result

Risky cancels cast times on the enemy

## Expected result

Cast time shouldn't be cancelled because there is no crowd control in the jutsu. The cast should continue going. 

**Affected Client Version:** 

Both clients, been around for a long time.

**Comment by RorySoh** [comment]
The bug is that it's not mentioned anywhere. The jutsu has cancel on it, so it's behaving as intended. Will fix the description.
