### ISSUE TITLE
Level 43 WM with 70 strength & can’t wield weapons 

### ISSUE THREAD

**Issue by zayhunna** [HitsparkInteractive/NinOnline#66]
## Spent 10 coupons on a stat reset , used the stat reset & can no longer wield any swords even though I have the required strength 

<< says I have 70 strength & im level 43 so why can’t I wield weapons that I previously was able to wield before I used the stat reset > 

I previously had 111 strength , 20 intellect & the rest in chak & fort . 

I reset so I can add more intellect & now this is the outcome . 

Hoping this can be fixed because I’m pretty much useless at this point . 
this happened right after the dodgeball event hosted by sushi & ueda . 
![891D08D6-A577-4291-8927-C970D738E9C9](https://user-images.githubusercontent.com/90075343/132077227-2b624794-6606-4a7f-b20d-91ca44b77b92.jpeg)
![0A45394E-F5B8-4069-A219-B3E5DDD20A52](https://user-images.githubusercontent.com/90075343/132077229-23d4750a-c52d-4bec-8a6a-d3008a4c7242.jpeg)
![EA9ED265-7859-4A6E-8BFD-C704A685328D](https://user-images.githubusercontent.com/90075343/132077232-ea31283e-3842-486e-b12e-c786773a6a71.jpeg)
![99475C3E-A3F6-499C-B2A9-123DD22D6BF3](https://user-images.githubusercontent.com/90075343/132077233-b740053b-8199-43f2-b301-2ab4b2c12363.jpeg)
![83AB40D7-EAC1-402F-A55D-6D7D0F8068E7](https://user-images.githubusercontent.com/90075343/132077238-dc259c59-41bd-4068-ac3b-d8d43c210455.jpeg)

**Comment by RorySoh** [comment]
Do you have any items equipped currently that add to your strength?

**Comment by zayhunna** [comment]
> Do you have any items equipped currently that add to your strength?

No I had nothing like that on although I was wielding a shirokata when I used the stat reset , which would remove the shiro anyways . (Says I disarm the shiro in the screenshot ) 
It says I have 70 strength but then the requirement on the sword is in Red writing for some reason

**Comment by RorySoh** [comment]
I've checked your account and you have 69 strength in our records.
May I login to your account to check what's up? I'll have to change your password.

**Comment by zayhunna** [comment]
> I've checked your account and you have 69 strength in our records.
> May I login to your account to check what's up? I'll have to change your password.

Yes ... this isn’t a scam right o_o 
Lol jk 
But on my end it says 
70 str 
50 int 
51 chak 
60 fort

**Comment by zayhunna** [comment]
> I've checked your account and you have 69 strength in our records.
> May I login to your account to check what's up? I'll have to change your password.

I messages you on forum to see if this is really ueda

**Comment by RorySoh** [comment]
As suspected, the bug was that Blue Furred Armor was unexpectedly giving +1 Strength due to some sort of data corruption.
Fixed, player will have stats reset.

**Comment by zayhunna** [comment]
Hey sorry I just logged in and recovered my password , I didn’t know if it
was ready for me right now
