### ISSUE TITLE
Game still crashes when I click "login"

### ISSUE THREAD

**Issue by Hadashah1** [HitsparkInteractive/NinOnline#68]
## Steps to reproduce issue

1.
2.
3.

## More details

**Affected Client Version:** 

**First noticed:** 

## Error Logs

<details><summary>View details</summary>

Game will not let me log. It crashes whenever I click "login." I have uninstalled and reinstalled many times. My friend reported this issue before and it was closed out, but I still have the same issue.

</details>

**Comment by RorySoh** [comment]
Can you try the 2nd article in this under Crashing Troubleshoot
https://www.ninonline.org/forum/troubleshoot/
