### ISSUE TITLE
Rez Altered Upon Logout (2560x1440)

### ISSUE THREAD

**Issue by Indie-Patron** [HitsparkInteractive/NinOnline#7]
**Problem description**
When I log in, my resolution is very low, but it is the same as when I log out in the options (2560x1440).

**Steps to reproduce issue**
Log out in fullscreen at 2560x1440.

**Observed Result**
Logging back in at a different resolution, it is not changable by using the options.
Also some different windows are oddly unresponsive, such as the login button, and the server choice. 
There is also no login art.

**Expected Result**
Logging in at the same resolution.

**Affected Client Version:** 0.5.9 (?)

**Comment by RorySoh** [comment]
This was probably due to me accidentally pushing the update with a configuration file, so it was replacing it with the default configuration each time you ran the updater. If this isn't the case and it is persisting, let me know!
