### ISSUE TITLE
Invisible wall bug

### ISSUE THREAD

**Issue by 0um** [HitsparkInteractive/NinOnline#70]
## Problem description

 Was running into some kind of invisible wall I recorded a few minutes of it before I got past it. https://www.youtube.com/watch?v=Pic5eWaD0Ag

## Steps to reproduce issue

1.
2.
3.

## More details

**Affected Client Version:** 

**First noticed:** 

## Error Logs

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by RorySoh** [comment]
https://github.com/HitsparkInteractive/NinOnline/issues/71

Combining with this report
