### ISSUE TITLE
Multiple disconnects

### ISSUE THREAD

**Issue by Xisdezenho** [HitsparkInteractive/NinOnline#75]
## Problem description
When I login the game, I stay connected for 5-15 seconds then the disconection comes and I get no error message, it just send me back to the login area... could you please help me?

## Steps to reproduce issue

1.
2.
3.

## More details

**Affected Client Version:** 

**First noticed:** 

## Error Logs

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by RorySoh** [comment]
Please follow the troubleshoot under disconnections
https://www.ninonline.org/forum/troubleshoot/
