### ISSUE TITLE
Accepting a trade request caused my nin music to start while it was at 0% volume and also a weird visual glitch

### ISSUE THREAD

**Issue by ryanara3** [HitsparkInteractive/NinOnline#78]
## Steps to reproduce issue

1.
2.
3.

## More details

**Affected Client Version:** 

**First noticed:** 

## Error Logs

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by RorySoh** [comment]
We are unable to replicate this with the instructions provided at this time.
We will continue to look out for this, so far this has been the only case of it happening.
