### ISSUE TITLE
Bought new laptop and people around me look like they are lagging

### ISSUE THREAD

**Issue by Melliel** [HitsparkInteractive/NinOnline#8]
Update!!!! **CONNECTION PROBLEM LAG SPIKE**

**Problem description**
I bought a new laptop Legion Lenovo 5 GTX 2060. I noticed that i have lag spike on nin every 3 second something like that. This doesnt happens on my old laptop.

**Steps to reproduce issue**
When people running or doing activity around me, if i afk in a house without people my ping is stable and no lag

Observed Result
People around me look like they are lagging all the time

Expected Result
No lag spike

For more information i can provide a video of my gameplay if needed. Contact Mell in discord

Affected Client Version: 0.5.9 (?)

**Comment by RorySoh** [comment]
Has this been improved since July? @Melliel
