### ISSUE TITLE
Previously fixed Agility Weapons hit register is bugged again

### ISSUE THREAD

**Issue by RaitouNin** [HitsparkInteractive/NinOnline#84]
## Problem description

When using any agility weapon every other attack animation does not damage the target

## Steps to reproduce issue

1. Equip any agility requirement weapon: Tonfas 70 agility, Blood tonfas 110 agility, Demon Claws 110 agility
2. Hold attack key while on an adjacent tile to a targeted player

## Observed result

Regardless of agility stat every other attack animation will not cause damage to the target

## Expected result

Every attack animation when holding attack against a player registers a hit

## More details
This issue was previously fixed for agility weapons in the April 13th ghost hit bug fix patch, the affected swords, fan, and pipe weapons remain fixed but the agility weapons have reverted to how they were before this patch,

**Affected Client Version:** 

This issue resurfaced on the new client some time in June 2021, it was a known issue on the old client the the new client aimed to fix, and did so, but it has since regressed.

**First noticed:** 
When I came back to the game in July 2021 I noticed the patch was reverted.

Here is how agility weapon attacks registered after the ghost hit bug fix in April 2021:

https://user-images.githubusercontent.com/91229216/134442345-0302ac4c-218d-4465-a1e3-c482938a7e9b.mp4

And this is how agility weapon attacks register on the current patch:

https://user-images.githubusercontent.com/91229216/134442354-c6f42141-2123-4af9-a845-f7c231eeb495.mp4

Thank you for taking the time to review this issue.

**Comment by RorySoh** [comment]
This seems linked to amount of Agility player has

**Comment by RorySoh** [comment]
Closing and adding to existing bug report

**Comment by RorySoh** [comment]
https://github.com/HitsparkInteractive/NinOnline/issues/60
