### ISSUE TITLE
Games freezing when cloaked entering a village

### ISSUE THREAD

**Issue by Yerashi** [HitsparkInteractive/NinOnline#87]
For a week or so now i've had an issue with the game freezing when i'm entering a village cloaked. it usually lasts for about 10 seconds. When it unfreezes i'm uncloaked being attacked by the jounin NPC's. It's happened consistantly enough for me to notice.

Update. Its not just when cloaked. I've entered the mist village uncloaked and same issue happens

**Comment by RorySoh** [comment]
This just seems like you're taking a long time to load large maps.
