### ISSUE TITLE
Cloaking on BI adds roughly two minutes to BI timer

### ISSUE THREAD

**Issue by TheKurai** [HitsparkInteractive/NinOnline#88]
my BI was at 20, and I cloaked to avoid bears, and when my cloak cast finished my BI timer jumped to 120.

**Comment by RorySoh** [comment]
@michaelsakharov There's been a lot of reports of this. I don't think it's that the BI timer actually increases, I think the timer in general is out of sync, and when another one ends (is cancel or expired) the server sends an update to all the player's buffs, correcting the desync.

----
Yes to confirm, that is the actual issue. To test this, I got Battle Injuries, a 500s timer began on the server.
I waited till it reached 0, and it stayed at 0 for around 30 seconds. After which, I used a buff and it raised it to 70 seconds, revealing the actual time of the buff on the server.

**Comment by RorySoh** [comment]
This has been resolved.
