### ISSUE TITLE
Devil wings offcenter/Not moving in Idle state

### ISSUE THREAD

**Issue by Mokuchi** [HitsparkInteractive/NinOnline#89]
## Problem description

 the wings are offcenter and do not move when idle (standing still)

## Steps to reproduce issue

 You stand still and they look off center and don't move
/

1.
2.
3.

## Observed result

/

## Expected result

 /

## More details
 details down below in images of the issue

**Affected Client Version:**  version of the game not relevant to issue

/

**First noticed:** 13 october 2021

## Error Logs

<details><summary>View details</summary>

PASTE HERE
![image](https://user-images.githubusercontent.com/87088478/137176765-17303641-dbbc-430a-913e-d9cb0e280397.png)

https://user-images.githubusercontent.com/87088478/137177232-6300ba3c-e161-43cd-8c62-4e2aba494708.mp4

</details>

**Comment by RorySoh** [comment]
Fixed in next update
(It wasn't off center though)
