### ISSUE TITLE
Maxed Great Bubble Shark damage is bugged

### ISSUE THREAD

**Issue by cardibeef** [HitsparkInteractive/NinOnline#90]
## Problem description

Maxed Great Bubble Shark only adds 1 damage instead of 5. The base damage is supposed to go from 29 to 34 but my damage only went from 60 to 61

## Steps to reproduce issue

1.
2.
3.

## More details

**Affected Client Version:** 

**First noticed:** 

## Error Logs

<details><summary>View details</summary>

![wtf](https://user-images.githubusercontent.com/92501873/137255415-dc0087a6-c713-4a09-83f0-50823c992e3a.png)

</details>

**Comment by RorySoh** [comment]
You might be referring to outdated information

**Comment by cardibeef** [comment]
@RorySoh so maxed bubble shark only increases its damage by 1? o.o
